name: End-to-end tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start the application server
      - name: Start application server
        run: npm start &
        env:
          CI: true

      # Wait for the server to be ready
      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v0.2.0
        with:
          timeout: 60
          url: 'http://localhost:3030'

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5

      # Upload screenshots (if any)
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload videos (always)
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
